### ISSUE TITLE
How to change partial Notch Colors and Drawable

### ISSUE THREAD

**Issue by pravingaikwad07** [DVegasa/ArcPointer#3]
I want to change colors specific notches. How to do it ? Say, I want to show percentage. Show if Percentage is 49 then 49 Notches should be of color red and rest should be of color black. How to achieve this. I tried changing color of notches but it changes color of the all the notches.

See image attached below for reference.

Thanks.

I want to do this 
![snap 2018-06-24 at 12 59 11](https://user-images.githubusercontent.com/13349805/41816927-b115f0a6-77ae-11e8-8aa9-5e63916e3725.png)

I am able to do this much only :
![snap 2018-06-24 at 13 03 05](https://user-images.githubusercontent.com/13349805/41816935-f42e4654-77ae-11e8-8b83-abe998d1af6d.png)

**Comment by DVegasa** [comment]
At the moment there is no possibility to change the color of a single notch. Within a week I'll try to add it, and maybe some other features about the notches.

A report on the work done will appear in this topic.

Thank you for your attention and participation in the development

**Comment by DVegasa** [comment]
A new version `1.0.2` has just been released

**ChangeLog**:
* Added customization of single notch:
  * Individual length
  * Individual color
  * Individual strokeWidth
* Old methods for working with notches have become deprecated

@pravingaikwad123, in your case you should use new method `setNotchesColors(float[] colors)`. It will set colors[i] color to notch[i]

*Thank you for your feedback.*
